repos:
  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12.0
        stages: [commit]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        stages: [commit]
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      language: system
      entry: pytest -vvv
      always_run: true
      pass_filenames: false 
      stages: [commit]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
